# Generated by Django 6.0.6 on 2026-09-25 01:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0003_bootstrap_prospecting'),
        ('projects', '0001_initial'),
        ('tenants', '0008_assistantprofile_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=220)),
                ('address', models.CharField(blank=True, max_length=260, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('maps_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('external_id', models.CharField(blank=True, max_length=180, null=True)),
                ('identity_key', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('category', models.CharField(blank=True, max_length=160, null=True)),
                ('address', models.CharField(blank=True, max_length=260, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('maps_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('external_id', models.CharField(blank=True, max_length=180, null=True)),
                ('source_query', models.CharField(blank=True, max_length=260, null=True)),
                ('dedupe_key', models.CharField(max_length=320)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProspectEnrichment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WEBSITE', 'Website'), ('DOMAIN', 'Domain'), ('ADDRESS', 'Address')], max_length=24)),
                ('value', models.CharField(max_length=1000)),
                ('normalized_value', models.CharField(max_length=1000)),
                ('source_type', models.CharField(choices=[('SEARCH_RESULT', 'Search result'), ('MANUAL', 'Manual'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_reference', models.CharField(blank=True, max_length=320)),
                ('source_key', models.CharField(max_length=420)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='prospecting.prospect')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_enrichments', to='tenants.tenant')),
                ('source_search_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect_enrichments', to='prospecting.searchresult')),
            ],
            options={
                'ordering': ['field', 'value'],
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('target_market', models.CharField(blank=True, max_length=180)),
                ('target_region', models.CharField(max_length=180)),
                ('target_profile', models.CharField(blank=True, max_length=180)),
                ('objective', models.TextField(blank=True)),
                ('queries', models.JSONField(default=list)),
                ('max_results', models.PositiveSmallIntegerField(default=10)),
                ('locale', models.CharField(default='pt-BR', max_length=16)),
                ('agent_platform_execution_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, unique=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_runs', to='agents.agentinstallation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_runs', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_runs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='prospecting.searchrun'),
        ),
        migrations.CreateModel(
            name='ProspectSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='prospecting.prospect')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_sources', to='tenants.tenant')),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_sources', to='prospecting.searchresult')),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_sources', to='prospecting.searchrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['tenant', 'identity_key'], name='prospecting_tenant__3a12da_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['tenant', 'display_name'], name='prospecting_tenant__f236ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(fields=('tenant', 'identity_key'), name='unique_prospect_identity_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='prospectenrichment',
            index=models.Index(fields=['tenant', 'prospect', 'field'], name='prospecting_tenant__aa903c_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectenrichment',
            index=models.Index(fields=['tenant', 'field', 'normalized_value'], name='prospecting_tenant__cad3b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospectenrichment',
            constraint=models.UniqueConstraint(fields=('tenant', 'prospect', 'field', 'normalized_value', 'source_key'), name='unique_prospect_enrichment_observation'),
        ),
        migrations.AddIndex(
            model_name='searchrun',
            index=models.Index(fields=['tenant', 'status'], name='prospecting_tenant__78b3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrun',
            index=models.Index(fields=['project', 'status'], name='prospecting_project_eaa34b_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['tenant', 'search_run'], name='prospecting_tenant__df06b5_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_run', 'dedupe_key'], name='prospecting_search__6afe55_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(fields=('search_run', 'dedupe_key'), name='unique_search_result_per_run_dedupe'),
        ),
        migrations.AddIndex(
            model_name='prospectsource',
            index=models.Index(fields=['tenant', 'prospect'], name='prospecting_tenant__1f9785_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectsource',
            index=models.Index(fields=['tenant', 'search_run'], name='prospecting_tenant__deb318_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospectsource',
            constraint=models.UniqueConstraint(fields=('search_result',), name='unique_prospect_source_per_search_result'),
        ),
        migrations.AddConstraint(
            model_name='prospectsource',
            constraint=models.UniqueConstraint(fields=('prospect', 'search_result'), name='unique_prospect_source_link'),
        ),
    ]
