# Generated by Django 6.0.6 on 2026-09-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0001_initial'),
        ('tenants', '0008_assistantprofile_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='review_status',
            field=models.CharField(choices=[('UNREVIEWED', 'Não revisado'), ('IGNORED', 'Ignorado')], default='UNREVIEWED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_run', 'review_status'], name='prospecting_search__f892c5_idx'),
        ),
    ]
