# Generated by Django 6.0.6 on 2026-09-25 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0002_searchresult_review_status_and_more'),
        ('tenants', '0008_assistantprofile_notification_email'),
        ('tools', '0007_serviceclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRunExecutionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_attempts', to='prospecting.searchrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_run_attempts', to='tenants.tenant')),
                ('tool_execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='search_run_attempt', to='tools.toolexecution')),
            ],
            options={
                'ordering': ['attempt_number'],
                'indexes': [models.Index(fields=['tenant', 'search_run'], name='prospecting_tenant__48e77f_idx'), models.Index(fields=['search_run', 'attempt_number'], name='prospecting_search__774331_idx')],
                'constraints': [models.UniqueConstraint(fields=('search_run', 'attempt_number'), name='unique_search_run_attempt_number')],
            },
        ),
    ]
