# Generated by Django 6.0.6 on 2026-09-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0004_prospect_qualification_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prospect',
            new_name='prospecting_tenant__f6d949_idx',
            old_name='prospecting_tenant__8a0f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='prospecting_tenant__3cf05d_idx',
            old_name='prospecting_tenant__c4e2a9_idx',
        ),
    ]
