# Generated by Django 6.0.6 on 2026-09-25 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0005_rename_prospecting_tenant__8a0f1d_idx_prospecting_tenant__f6d949_idx_and_more'),
        ('tenants', '0008_assistantprofile_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=220)),
                ('role_title', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.CharField(blank=True, default='', max_length=320)),
                ('phone', models.CharField(blank=True, default='', max_length=80)),
                ('normalized_email', models.CharField(blank=True, default='', max_length=320)),
                ('normalized_phone', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('WEBSITE', 'Website'), ('ENRICHMENT', 'Enrichment'), ('OTHER', 'Other')], default='MANUAL', max_length=16)),
                ('source_reference', models.CharField(blank=True, default='', max_length=320)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='prospecting.prospect')),
                ('source_enrichment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_contacts', to='prospecting.prospectenrichment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_contacts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'email', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'prospect'], name='prospecting_tenant__8260b1_idx'), models.Index(fields=['tenant', 'prospect', 'normalized_email'], name='prospecting_tenant__d1d9b2_idx'), models.Index(fields=['tenant', 'prospect', 'normalized_phone'], name='prospecting_tenant__4cdb5b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('normalized_email__gt', '')), fields=('tenant', 'prospect', 'normalized_email'), name='unique_prospect_contact_email_per_prospect'), models.UniqueConstraint(condition=models.Q(('normalized_phone__gt', '')), fields=('tenant', 'prospect', 'normalized_phone'), name='unique_prospect_contact_phone_per_prospect')],
            },
        ),
    ]
