# Generated by Django 6.0.6 on 2026-09-25 21:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0006_prospectcontact'),
        ('tenants', '0008_assistantprofile_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('NOTE', 'Nota'), ('CALL', 'Ligação'), ('MEETING', 'Reunião'), ('CONTACT_ATTEMPT', 'Tentativa de contato'), ('REPLY_RECEIVED', 'Retorno recebido'), ('VISIT', 'Visita'), ('OTHER', 'Outro')], default='NOTE', max_length=24)),
                ('note', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='prospecting.prospectcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_activities_created', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='prospecting.prospect')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_activities', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'prospect', 'occurred_at'], name='prospecting_tenant__83f846_idx'), models.Index(fields=['tenant', 'prospect', 'activity_type'], name='prospecting_tenant__35fa67_idx')],
            },
        ),
    ]
