# Generated by Django 6.0.6 on 2026-09-25 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0007_prospectactivity'),
        ('tenants', '0008_assistantprofile_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectOutreachDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Outro')], max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=220)),
                ('body', models.TextField()),
                ('destination_email', models.CharField(blank=True, default='', max_length=320)),
                ('destination_phone', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('READY', 'Pronto'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=16)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_drafts', to='prospecting.prospectcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_outreach_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_drafts', to='prospecting.prospect')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_outreach_drafts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'prospect', 'status'], name='prospecting_tenant__803e61_idx'), models.Index(fields=['tenant', 'prospect', 'channel'], name='prospecting_tenant__774d32_idx')],
            },
        ),
    ]
