# Generated by Django 6.0.6 on 2026-09-25 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0008_prospectoutreachdraft'),
        ('tenants', '0008_assistantprofile_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectactivity',
            name='activity_type',
            field=models.CharField(choices=[('NOTE', 'Nota'), ('CALL', 'Ligação'), ('MEETING', 'Reunião'), ('CONTACT_ATTEMPT', 'Tentativa de contato'), ('EMAIL_SENT', 'E-mail enviado'), ('REPLY_RECEIVED', 'Retorno recebido'), ('VISIT', 'Visita'), ('OTHER', 'Outro')], default='NOTE', max_length=24),
        ),
        migrations.CreateModel(
            name='ProspectOutreachSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Outro')], max_length=16)),
                ('destination', models.CharField(max_length=320)),
                ('subject_snapshot', models.CharField(blank=True, default='', max_length=220)),
                ('body_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('FAILED', 'Falha'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=16)),
                ('provider', models.CharField(choices=[('DJANGO_EMAIL', 'Django email')], default='DJANGO_EMAIL', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=220)),
                ('idempotency_key', models.CharField(max_length=220, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_sends', to='prospecting.prospectcontact')),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_send', to='prospecting.prospectoutreachdraft')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_sends', to='prospecting.prospect')),
                ('prospect_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_outreach_send', to='prospecting.prospectactivity')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_outreach_sends_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_outreach_sends', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'prospect', 'status'], name='prospecting_tenant__fe660c_idx'), models.Index(fields=['tenant', 'draft'], name='prospecting_tenant__a8a6ee_idx')],
            },
        ),
    ]
