# Generated by Django 6.0.6 on 2026-09-25 23:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0009_alter_prospectactivity_activity_type_and_more'),
        ('tenants', '0008_assistantprofile_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectContactOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('AWAITING_RESPONSE', 'Aguardando retorno'), ('INTERESTED', 'Interessado'), ('CALLBACK_REQUESTED', 'Pediu retorno'), ('NOT_INTERESTED', 'Sem interesse'), ('NO_RESPONSE', 'Sem resposta'), ('OTHER', 'Outro')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_outcomes', to='prospecting.prospectcontact')),
                ('outreach_send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_outcomes', to='prospecting.prospectoutreachsend')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_outcomes', to='prospecting.prospect')),
                ('prospect_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_contact_outcome', to='prospecting.prospectactivity')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_contact_outcomes_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_contact_outcomes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CALL', 'Ligação'), ('EMAIL', 'E-mail'), ('MEETING', 'Reunião'), ('VISIT', 'Visita'), ('REVIEW', 'Revisar'), ('OTHER', 'Outro')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_follow_ups_completed', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='prospecting.prospectcontact')),
                ('contact_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='prospecting.prospectcontactoutcome')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_follow_ups_created', to=settings.AUTH_USER_MODEL)),
                ('outreach_send', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='prospecting.prospectoutreachsend')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='prospecting.prospect')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_follow_ups', to='tenants.tenant')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prospectcontactoutcome',
            index=models.Index(fields=['tenant', 'prospect', 'outcome'], name='prospecting_tenant__19f8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectcontactoutcome',
            index=models.Index(fields=['tenant', 'prospect', 'occurred_at'], name='prospecting_tenant__bf6efd_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectfollowup',
            index=models.Index(fields=['tenant', 'prospect', 'status'], name='prospecting_tenant__a6d351_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectfollowup',
            index=models.Index(fields=['tenant', 'prospect', 'due_at'], name='prospecting_tenant__e7dda2_idx'),
        ),
    ]
