# Generated by Codex on 2026-09-20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("tenants", "0008_assistantprofile_notification_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("agent_type", models.CharField(max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["slug"]},
        ),
        migrations.CreateModel(
            name="AgentVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=40)),
                ("runtime_handler", models.CharField(max_length=80)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("deprecated", "Deprecated")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_definition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="agents.agentdefinition")),
            ],
            options={"ordering": ["agent_definition__slug", "-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("is_enabled", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="installations", to="agents.agentdefinition")),
                ("agent_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="installations", to="agents.agentversion")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_installations", to="projects.project")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_installations", to="tenants.tenant")),
            ],
            options={"ordering": ["tenant__name", "project__name", "name"]},
        ),
        migrations.AddConstraint(
            model_name="agentversion",
            constraint=models.UniqueConstraint(fields=("agent_definition", "version"), name="unique_agent_version_per_definition"),
        ),
        migrations.AddIndex(
            model_name="agentinstallation",
            index=models.Index(fields=["tenant", "is_enabled"], name="agents_agen_tenant__14fdda_idx"),
        ),
        migrations.AddIndex(
            model_name="agentinstallation",
            index=models.Index(fields=["project", "is_enabled"], name="agents_agen_project_041c81_idx"),
        ),
    ]
