# Generated by Codex on 2026-09-20

from django.db import migrations


def bootstrap_livia(apps, schema_editor):
    AgentDefinition = apps.get_model("agents", "AgentDefinition")
    AgentVersion = apps.get_model("agents", "AgentVersion")

    definition, _ = AgentDefinition.objects.update_or_create(
        slug="livia",
        defaults={
            "name": "Lívia",
            "description": "Legacy Lívia conversational sales agent.",
            "agent_type": "conversational_sales",
            "is_active": True,
        },
    )
    AgentVersion.objects.update_or_create(
        agent_definition=definition,
        version="legacy-initial",
        defaults={
            "runtime_handler": "livia",
            "status": "active",
        },
    )


def unbootstrap_livia(apps, schema_editor):
    AgentDefinition = apps.get_model("agents", "AgentDefinition")
    AgentDefinition.objects.filter(slug="livia").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(bootstrap_livia, unbootstrap_livia),
    ]
