# Generated by Codex on 2026-09-20

from django.db import migrations


def bootstrap_prospecting(apps, schema_editor):
    AgentDefinition = apps.get_model("agents", "AgentDefinition")
    AgentVersion = apps.get_model("agents", "AgentVersion")

    definition, _ = AgentDefinition.objects.update_or_create(
        slug="prospecting",
        defaults={
            "name": "Prospecting Agent",
            "description": "Agente responsável por planejamento e execução futura de atividades de prospecção comercial.",
            "agent_type": "sales_prospecting",
            "is_active": True,
        },
    )
    AgentVersion.objects.update_or_create(
        agent_definition=definition,
        version="1.0.0",
        defaults={
            "runtime_handler": "prospecting",
            "status": "active",
        },
    )


def unbootstrap_prospecting(apps, schema_editor):
    AgentDefinition = apps.get_model("agents", "AgentDefinition")
    AgentDefinition.objects.filter(slug="prospecting").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_bootstrap_livia"),
    ]

    operations = [
        migrations.RunPython(bootstrap_prospecting, unbootstrap_prospecting),
    ]
