# Generated by Codex on 2026-09-20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0008_assistantprofile_notification_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="tenants.tenant"),
                ),
            ],
            options={
                "ordering": ["tenant__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(fields=("tenant", "slug"), name="unique_project_slug_per_tenant"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "is_active"], name="projects_pr_tenant__7a3568_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant", "slug"], name="projects_pr_tenant__2519ff_idx"),
        ),
    ]
