# Generated by Django 6.0.6 on 2026-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0020_ragretrievalevent_retrieval_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantragdrivefilemanifest',
            name='status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('exported', 'Exported'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped_unsupported', 'Skipped unsupported'), ('skipped_temporary_artifact', 'Skipped temporary artifact'), ('failed', 'Failed'), ('removed', 'Removed'), ('unavailable', 'Unavailable')], default='discovered', max_length=30),
        ),
    ]
