from django.urls import path

from . import views

app_name = "control_plane"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("tenants/", views.tenant_list, name="tenant_list"),
    path("tenants/<int:pk>/", views.tenant_detail, name="tenant_detail"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/new/", views.project_create, name="project_create"),
    path("projects/<uuid:pk>/", views.project_detail, name="project_detail"),
    path("projects/<uuid:project_id>/install-agent/", views.install_agent, name="install_agent"),
    path("agents/", views.agent_list, name="agent_list"),
    path("agents/<uuid:pk>/", views.agent_detail, name="agent_detail"),
    path("tools/", views.tool_list, name="tool_list"),
    path("tools/<uuid:pk>/", views.tool_detail, name="tool_detail"),
    path("tool-executions/", views.tool_execution_list, name="tool_execution_list"),
    path("tool-executions/<uuid:pk>/", views.tool_execution_detail, name="tool_execution_detail"),
    path("service-clients/", views.service_client_list, name="service_client_list"),
    path("service-clients/<uuid:pk>/", views.service_client_detail, name="service_client_detail"),
    path("service-clients/<uuid:pk>/credentials/create/", views.service_client_credential_create, name="service_client_credential_create"),
    path("service-client-credentials/<uuid:pk>/revoke/", views.service_client_credential_revoke, name="service_client_credential_revoke"),
    path("service-client-credentials/<uuid:pk>/rotate/", views.service_client_credential_rotate, name="service_client_credential_rotate"),
    path("service-clients/<uuid:pk>/access/grant/", views.service_client_access_grant, name="service_client_access_grant"),
    path("service-client-accesses/<uuid:pk>/revoke/", views.service_client_access_revoke, name="service_client_access_revoke"),
    path("executors/", views.executor_list, name="executor_list"),
    path("executors/<uuid:pk>/", views.executor_detail, name="executor_detail"),
    path("executors/<uuid:pk>/capabilities/add/", views.executor_capability_add, name="executor_capability_add"),
    path("executor-capabilities/<uuid:pk>/enable/", views.executor_capability_enable, name="executor_capability_enable"),
    path("executor-capabilities/<uuid:pk>/disable/", views.executor_capability_disable, name="executor_capability_disable"),
    path("executor-pairings/", views.executor_pairing_list, name="executor_pairing_list"),
    path("executor-pairings/<uuid:pk>/approve/", views.executor_pairing_approve, name="executor_pairing_approve"),
    path("executor-pairings/<uuid:pk>/reject/", views.executor_pairing_reject, name="executor_pairing_reject"),
    path("executor-credentials/<uuid:pk>/revoke/", views.executor_credential_revoke, name="executor_credential_revoke"),
    path("executor-credentials/<uuid:pk>/rotate/", views.executor_credential_rotate, name="executor_credential_rotate"),
    path("installations/<uuid:installation_id>/tools/add/", views.installation_add_tool, name="installation_add_tool"),
    path("tool-bindings/<uuid:pk>/edit/", views.tool_binding_edit, name="tool_binding_edit"),
    path("tool-bindings/<uuid:pk>/enable/", views.tool_binding_enable, name="tool_binding_enable"),
    path("tool-bindings/<uuid:pk>/disable/", views.tool_binding_disable, name="tool_binding_disable"),
    path("installations/", views.installation_list, name="installation_list"),
    path("installations/<uuid:pk>/", views.installation_detail, name="installation_detail"),
    path("installations/<uuid:pk>/enable/", views.installation_enable, name="installation_enable"),
    path("installations/<uuid:pk>/disable/", views.installation_disable, name="installation_disable"),
]
