"""Resumo comercial da conversa da Lívia."""

from .livia import (
    MAX_COMMERCIAL_TRANSCRIPT_CHARS,
    MAX_TRANSCRIPT_CHARS,
    MAX_TRANSCRIPT_TURNS,
    ConversationSummary,
    build_commercial_notification_html,
    build_commercial_notification_transcript,
    build_conversation_summary,
    build_conversation_transcript,
    build_handoff_notification_body,
    build_handoff_notification_subject,
    build_lead_notification_body,
    build_lead_notification_subject,
    build_lead_notification_summary_text,
    format_conversation_summary_notes,
    get_commercial_transcript_truncation_notice,
    get_transcript_truncation_notice,
    resolve_commercial_intent_label,
)

__all__ = [
    "MAX_COMMERCIAL_TRANSCRIPT_CHARS",
    "MAX_TRANSCRIPT_CHARS",
    "MAX_TRANSCRIPT_TURNS",
    "ConversationSummary",
    "build_commercial_notification_html",
    "build_commercial_notification_transcript",
    "build_conversation_summary",
    "build_conversation_transcript",
    "build_handoff_notification_body",
    "build_handoff_notification_subject",
    "build_lead_notification_body",
    "build_lead_notification_subject",
    "build_lead_notification_summary_text",
    "format_conversation_summary_notes",
    "get_commercial_transcript_truncation_notice",
    "get_transcript_truncation_notice",
    "resolve_commercial_intent_label",
]
