# Generated by Django 6.0.6 on 2026-09-20 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0003_bootstrap_prospecting'),
        ('projects', '0001_initial'),
        ('tenants', '0008_assistantprofile_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=80)),
                ('runtime_handler', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bindings', to='agents.agentinstallation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_bindings', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_bindings', to='tenants.tenant')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_bindings', to='tools.tooldefinition')),
            ],
            options={
                'ordering': ['tenant__name', 'project__name', 'tool_definition__slug'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='tools_agent_tenant__72b269_idx'), models.Index(fields=['project', 'is_enabled'], name='tools_agent_project_13eac2_idx'), models.Index(fields=['agent_installation', 'is_enabled'], name='tools_agent_agent_i_7fc656_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent_installation', 'tool_definition'), name='unique_tool_binding_per_installation')],
            },
        ),
    ]
