# Generated by Django 6.0.6 on 2026-09-20 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_bootstrap_prospecting'),
        ('projects', '0001_initial'),
        ('tenants', '0008_assistantprofile_notification_email'),
        ('tools', '0002_bootstrap_prospecting_build_search_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldefinition',
            name='execution_mode',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('DELEGATED', 'Delegated')], default='LOCAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='runtime_handler',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ToolExecutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('executor_type', models.CharField(choices=[('BROWSER_EXTENSION', 'Browser extension'), ('SMART_SALES', 'Smart Sales'), ('WORKER', 'Worker')], max_length=32)),
                ('public_id', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_mode', models.CharField(choices=[('LOCAL', 'Local'), ('DELEGATED', 'Delegated')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='agents.agentinstallation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='tenants.tenant')),
                ('tool_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='tools.agenttoolbinding')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='tools.tooldefinition')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='tools.toolexecutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecutorCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='tools.toolexecutor')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_capabilities', to='tools.tooldefinition')),
            ],
            options={
                'ordering': ['executor__name', 'tool_definition__slug'],
            },
        ),
        migrations.AddIndex(
            model_name='toolexecutor',
            index=models.Index(fields=['tenant', 'is_active'], name='tools_toole_tenant__f9f09f_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecutor',
            index=models.Index(fields=['public_id', 'is_active'], name='tools_toole_public__9d6322_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tenant', 'status'], name='tools_toole_tenant__879916_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['project', 'status'], name='tools_toole_project_444221_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_definition', 'status'], name='tools_toole_tool_de_3c2195_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['executor', 'status'], name='tools_toole_executo_433670_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['execution_mode', 'status'], name='tools_toole_executi_01cdcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'agent_installation', 'tool_definition', 'idempotency_key'), name='unique_tool_execution_idempotency_context'),
        ),
        migrations.AddIndex(
            model_name='toolexecutorcapability',
            index=models.Index(fields=['executor', 'is_enabled'], name='tools_toole_executo_344171_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecutorcapability',
            index=models.Index(fields=['tool_definition', 'is_enabled'], name='tools_toole_tool_de_8c773b_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolexecutorcapability',
            constraint=models.UniqueConstraint(fields=('executor', 'tool_definition'), name='unique_tool_executor_capability'),
        ),
    ]
