# Generated by Django 6.0.6 on 2026-09-21 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_assistantprofile_notification_email'),
        ('tools', '0004_bootstrap_external_search_probe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolExecutorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_prefix', models.CharField(max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tools.toolexecutor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['credential_prefix'], name='tools_toole_credent_0d1072_idx'), models.Index(fields=['executor', 'is_active'], name='tools_toole_executo_b1e48d_idx'), models.Index(fields=['expires_at'], name='tools_toole_expires_64d14a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolExecutorPairingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executor_type', models.CharField(choices=[('BROWSER_EXTENSION', 'Browser extension'), ('SMART_SALES', 'Smart Sales'), ('WORKER', 'Worker')], max_length=32)),
                ('requested_name', models.CharField(max_length=160)),
                ('pairing_code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tool_executor_pairings', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_requests', to='tools.toolexecutor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executor_pairings', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tools_toole_tenant__6d61ae_idx'), models.Index(fields=['pairing_code'], name='tools_toole_pairing_ffd961_idx'), models.Index(fields=['status'], name='tools_toole_status_9b82bb_idx'), models.Index(fields=['expires_at'], name='tools_toole_expires_06cb60_idx')],
            },
        ),
    ]
