# Generated by Django 6.0.6 on 2026-09-23 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_bootstrap_prospecting'),
        ('tenants', '0008_assistantprofile_notification_email'),
        ('tools', '0006_bootstrap_google_maps_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_clients', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='requested_by_service_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_tool_executions', to='tools.serviceclient'),
        ),
        migrations.CreateModel(
            name='ServiceClientAgentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_execute', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_client_accesses', to='agents.agentinstallation')),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_accesses', to='tools.serviceclient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_client_agent_accesses', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name', 'service_client__name', 'agent_installation__name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceClientCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_prefix', models.CharField(max_length=32, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tools.serviceclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceclient',
            index=models.Index(fields=['tenant', 'is_active'], name='tools_servi_tenant__940532_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclient',
            index=models.Index(fields=['tenant', 'slug'], name='tools_servi_tenant__8f651f_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceclient',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_service_client_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='serviceclientagentaccess',
            index=models.Index(fields=['tenant', 'is_active'], name='tools_servi_tenant__65e4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclientagentaccess',
            index=models.Index(fields=['service_client', 'is_active'], name='tools_servi_service_de69aa_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclientagentaccess',
            index=models.Index(fields=['agent_installation', 'is_active'], name='tools_servi_agent_i_d1967b_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceclientagentaccess',
            constraint=models.UniqueConstraint(fields=('service_client', 'agent_installation'), name='unique_service_client_access_per_installation'),
        ),
        migrations.AddIndex(
            model_name='serviceclientcredential',
            index=models.Index(fields=['credential_prefix'], name='tools_servi_credent_7ceb21_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclientcredential',
            index=models.Index(fields=['service_client', 'is_active'], name='tools_servi_service_e2c8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclientcredential',
            index=models.Index(fields=['expires_at'], name='tools_servi_expires_bf9578_idx'),
        ),
    ]
